_wandb:
    value:
        cli_version: 0.23.1
        e:
            ba092hjnwaivmhx4q4rpht4en3k9rstj:
                codePath: src\pneumonia\train.py
                codePathLocal: src\pneumonia\train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "999012954112"
                        used: "610671792128"
                email: andreas.r.p@hotmail.com
                executable: C:\Users\andre\Desktop\Job\mlops\pneumonia_classification\.venv\Scripts\python.exe
                git:
                    commit: f92f35c47ec9e45fa72cb7066581a280ab0edc5a
                    remote: https://github.com/Dynamic-Duo-AT/pneumonia_classification.git
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5888
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-9d1fd6a0-9632-bfe2-64fd-3725dfb93fa0
                host: DESKTOP-5L4VT8F
                memory:
                    total: "34248056832"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\andre\Desktop\Job\mlops\pneumonia_classification\src\pneumonia\train.py
                python: CPython 3.12.12
                root: C:\Users\andre\Desktop\Job\mlops\pneumonia_classification
                startedAt: "2026-01-11T20:59:36.989773Z"
                writerId: ba092hjnwaivmhx4q4rpht4en3k9rstj
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 1
lr:
    value: 0.001
