workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/pneumonia-484312/artifact-container-docker/trainer:latest
        env:
        - name: WANDB_API_KEY
          value: <KEY>