_wandb:
    value:
        cli_version: 0.23.1
        e:
            h5ag0h078rnjk9rqbvpousaiviv1ivys:
                codePath: src/pneumonia/train.py
                codePathLocal: src/pneumonia/train.py
                email: tanneswl@outlook.com
                executable: /Users/tanne/Library/CloudStorage/OneDrive-DanmarksTekniskeUniversitet/MatModKandidat/MLOps/pneumonia_classicication/.venv/bin/python3
                git:
                    commit: dd0d634c5adfd9041e89f80f77f7ea566e2abb74
                    remote: https://github.com/Dynamic-Duo-AT/pneumonia_classification.git
                host: MacBookAir.zyxel.com
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/tanne/Library/CloudStorage/OneDrive-DanmarksTekniskeUniversitet/MatModKandidat/MLOps/pneumonia_classicication/src/pneumonia/train.py
                python: CPython 3.12.12
                root: /Users/tanne/Library/CloudStorage/OneDrive-DanmarksTekniskeUniversitet/MatModKandidat/MLOps/pneumonia_classicication
                startedAt: "2026-01-11T20:39:07.853863Z"
                writerId: h5ag0h078rnjk9rqbvpousaiviv1ivys
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 1
lr:
    value: 0.001
